nodeLinker: node-modules

plugins:
  - checksum: 18e2d554077ede391ce729e770d8de6b2242a429489d338046888a888a7f2f32d0fb573e5bed8fc316b9c72dfa6a82b6308404db320749f667c2a1b340720f5d
    path: .yarn/plugins/@yarnpkg/plugin-script-daemon.cjs
    spec: "https://raw.githubusercontent.com/zwade/yarn-plugin-script-daemon/refs/heads/master/bundles/%40yarnpkg/plugin-script-daemon.js"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
