// This file was generated by piqued.
// You can edit it if you want, but you'll probably be sad
// If you have some changes you want to make, check out the configuration options
// Or file a bug report on our definitely-extant github


export namespace Person {
    export const name = "person";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "email": string;
        "phone_number": string | null;
        "system_admin_witness": string | null;
        "pds_person_uid": string | null;
        "first_name": string;
        "last_name": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["email", String],
            ["phone_number", String],
            ["system_admin_witness", String],
            ["pds_person_uid", String],
            ["first_name", String],
            ["last_name", String],
        ] as const,
    };
}

export namespace UserAuth {
    export const name = "user_auth";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "username": string;
        "password_hash": string;
        "person_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["username", String],
            ["password_hash", String],
            ["person_uid", String],
        ] as const,
    };
}

export namespace AuthToken {
    export const name = "auth_token";
    
    export type t = {
        "token": string;
        "user_auth_uid": string | null;
        "expires_at": Date;
        "active_practice_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["token", String],
            ["user_auth_uid", String],
            ["expires_at", Date],
            ["active_practice_uid", String],
        ] as const,
    };
}

export namespace Practice {
    export const name = "practice";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "name": string;
        "domain": string;
        "requires_two_factor": boolean;
        "time_zone": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["name", String],
            ["domain", String],
            ["requires_two_factor", Boolean],
            ["time_zone", String],
        ] as const,
    };
}

export namespace ChatMessageData {
    export const name = "chat_message_data";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "content": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["content", String],
        ] as const,
    };
}

export namespace ChatMessage {
    export const name = "chat_message";
    
    export type t = {
        "sender_uid": string;
        "receiver_uid": string;
        "sequence_id": number;
        "created_at": Date;
        "expires_at": Date | null;
        "message_data_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["sender_uid", String],
            ["receiver_uid", String],
            ["sequence_id", Number],
            ["created_at", Date],
            ["expires_at", Date],
            ["message_data_uid", String],
        ] as const,
    };
}

export namespace PersonChallenge {
    export const name = "person_challenge";
    
    export type t = {
        "person_uid": string;
        "challenge": string;
        "expires_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["person_uid", String],
            ["challenge", String],
            ["expires_at", Date],
        ] as const,
    };
}

export namespace PersonAuthenticator {
    export const name = "person_authenticator";
    
    export type t = {
        "person_uid": string;
        "credential_id": string;
        "credential_public_key": string;
        "counter": number;
        "credential_device_type": string;
        "credential_backed_up": boolean;
        "transports": string[];
        "friendly_name": string;
        "created_at": Date;
        "last_used": Date | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["person_uid", String],
            ["credential_id", String],
            ["credential_public_key", String],
            ["counter", Number],
            ["credential_device_type", String],
            ["credential_backed_up", Boolean],
            ["transports", { "kind": "array", "spec": String }],
            ["friendly_name", String],
            ["created_at", Date],
            ["last_used", Date],
        ] as const,
    };
}

export namespace PharmacyItem {
    export const name = "pharmacy_item";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "sku": string;
        "name": string;
        "description": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["sku", String],
            ["name", String],
            ["description", String],
        ] as const,
    };
}

export namespace PracticeItemInventory {
    export const name = "practice_item_inventory";
    
    export type t = {
        "practice_uid": string;
        "pharmacy_item_uid": string;
        "current_quantity": number;
        "available_quantity": number;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["practice_uid", String],
            ["pharmacy_item_uid", String],
            ["current_quantity", Number],
            ["available_quantity", Number],
        ] as const,
    };
}

export namespace ShippingAddress {
    export const name = "shipping_address";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "person_uid": string | null;
        "street": string;
        "street2": string | null;
        "street3": string | null;
        "city": string | null;
        "state": string | null;
        "postal_code": string | null;
        "country": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["street", String],
            ["street2", String],
            ["street3", String],
            ["city", String],
            ["state", String],
            ["postal_code", String],
            ["country", String],
        ] as const,
    };
}

export namespace ShippingOrder {
    export const name = "shipping_order";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "status": ShippingStatus.t;
        "shipping_address_uid": string | null;
        "practice_uid": string | null;
        "patient_uid": string | null;
        "tracking_number": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["status", ShippingStatus.spec],
            ["shipping_address_uid", String],
            ["practice_uid", String],
            ["patient_uid", String],
            ["tracking_number", String],
        ] as const,
    };
}

export namespace ShippingOrderItem {
    export const name = "shipping_order_item";
    
    export type t = {
        "shipping_order_uid": string;
        "pharmacy_item_uid": string;
        "quantity": number;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["shipping_order_uid", String],
            ["pharmacy_item_uid", String],
            ["quantity", Number],
        ] as const,
    };
}

export namespace PatientMedication {
    export const name = "patient_medication";
    
    export type t = {
        "patient_uid": string;
        "pharmacy_item_uid": string;
        "created_at": Date;
        "updated_at": Date;
        "status": MedicationStatus.t;
        "dosage": string | null;
        "roa": string | null;
        "date_last_script": Date | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["patient_uid", String],
            ["pharmacy_item_uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["status", MedicationStatus.spec],
            ["dosage", String],
            ["roa", String],
            ["date_last_script", Date],
        ] as const,
    };
}

export namespace PatientAdherenceEvent {
    export const name = "patient_adherence_event";
    
    export type t = {
        "patient_uid": string;
        "pharmacy_item_uid": string;
        "created_at": Date;
        "event_type": string;
        "event_data": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["patient_uid", String],
            ["pharmacy_item_uid", String],
            ["created_at", Date],
            ["event_type", String],
            ["event_data", Object],
        ] as const,
    };
}

export namespace Fsm {
    export const name = "fsm";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "name": string;
        "description": string | null;
        "practice_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["name", String],
            ["description", String],
            ["practice_uid", String],
        ] as const,
    };
}

export namespace FsmNode {
    export const name = "fsm_node";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "name": string;
        "kind": FsmNodeKind.t;
        "description": string | null;
        "options": any;
        "fsm_uid": string;
        "is_start": boolean;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["name", String],
            ["kind", FsmNodeKind.spec],
            ["description", String],
            ["options", Object],
            ["fsm_uid", String],
            ["is_start", Boolean],
        ] as const,
    };
}

export namespace FsmEdge {
    export const name = "fsm_edge";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "start_node_uid": string;
        "end_node_uid": string;
        "trigger": FsmEdgeTrigger.t;
        "description": string | null;
        "options": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["start_node_uid", String],
            ["end_node_uid", String],
            ["trigger", FsmEdgeTrigger.spec],
            ["description", String],
            ["options", Object],
        ] as const,
    };
}

export namespace FsmInstance {
    export const name = "fsm_instance";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "fsm_uid": string;
        "patient_uid": string;
        "current_node_uid": string;
        "last_event_time": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["fsm_uid", String],
            ["patient_uid", String],
            ["current_node_uid", String],
            ["last_event_time", Date],
        ] as const,
    };
}

export namespace Message {
    export const name = "message";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "sender_uid": string | null;
        "recipient_uid": string | null;
        "encrypted_content": string;
        "channel": Channel.t;
        "secure": boolean;
        "revoked": boolean;
        "status": MessageStatus.t;
        "mode": MessageMode.t;
        "processed": boolean;
        "campaign_uid": string | null;
        "subject": string;
        "practice_phone_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["sender_uid", String],
            ["recipient_uid", String],
            ["encrypted_content", String],
            ["channel", Channel.spec],
            ["secure", Boolean],
            ["revoked", Boolean],
            ["status", MessageStatus.spec],
            ["mode", MessageMode.spec],
            ["processed", Boolean],
            ["campaign_uid", String],
            ["subject", String],
            ["practice_phone_uid", String],
        ] as const,
    };
}

export namespace Program {
    export const name = "program";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "slug": string;
        "version": number;
        "name": string;
        "description": string;
        "hlil": string;
        "llil": any;
        "mlil": any;
        "prompt": string;
        "practice_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["slug", String],
            ["version", Number],
            ["name", String],
            ["description", String],
            ["hlil", String],
            ["llil", Object],
            ["mlil", Object],
            ["prompt", String],
            ["practice_uid", String],
        ] as const,
    };
}

export namespace FtState {
    export const name = "ft_state";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "program_uid": string;
        "state": any;
        "selected_fds": number[];
        "active": boolean;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["program_uid", String],
            ["state", Object],
            ["selected_fds", { "kind": "array", "spec": Number }],
            ["active", Boolean],
        ] as const,
    };
}

export namespace ChannelFd {
    export const name = "channel_fd";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "kind": ChannelKind.t;
        "fd_state_uid": string;
        "fd": number;
        "name": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["kind", ChannelKind.spec],
            ["fd_state_uid", String],
            ["fd", Number],
            ["name", String],
        ] as const,
    };
}

export namespace PdsSystem {
    export const name = "pds_system";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "name": string;
        "description": string;
        "practice_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["name", String],
            ["description", String],
            ["practice_uid", String],
        ] as const,
    };
}

export namespace PdsRegistration {
    export const name = "pds_registration";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_system_uid": string;
        "credentials": string;
        "protocol": PdsRegistrationProtocol.t;
        "uri": string | null;
        "ingress": boolean;
        "egress": boolean;
        "delimiter": string;
        "format": PdsRegistrationFormat.t | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["credentials", String],
            ["protocol", PdsRegistrationProtocol.spec],
            ["uri", String],
            ["ingress", Boolean],
            ["egress", Boolean],
            ["delimiter", String],
            ["format", PdsRegistrationFormat.spec],
        ] as const,
    };
}

export namespace PdsFile {
    export const name = "pds_file";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "status": PdsFileStatus.t;
        "name": string;
        "data": Buffer;
        "pds_registration_uid": string | null;
        "last_ingested_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["status", PdsFileStatus.spec],
            ["name", String],
            ["data", Buffer],
            ["pds_registration_uid", String],
            ["last_ingested_at", Date],
        ] as const,
    };
}

export namespace PdsFileBatch {
    export const name = "pds_file_batch";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_file_uid": string;
        "sequence_id": number;
        "status": PdsFileBatchStatus.t;
        "data": any;
        "error": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_file_uid", String],
            ["sequence_id", Number],
            ["status", PdsFileBatchStatus.spec],
            ["data", Object],
            ["error", Object],
        ] as const,
    };
}

export namespace PdsAddress {
    export const name = "pds_address";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_system_uid": string;
        "entity_id": string;
        "line1": string | null;
        "line2": string | null;
        "city": string | null;
        "state": string | null;
        "zip": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["line1", String],
            ["line2", String],
            ["city", String],
            ["state", String],
            ["zip", String],
        ] as const,
    };
}

export namespace PdsPerson {
    export const name = "pds_person";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_system_uid": string;
        "entity_id": string;
        "first_name": string;
        "last_name": string;
        "email": string | null;
        "phone": string | null;
        "has_consent_marketing": boolean | null;
        "medical_record_number": string | null;
        "date_of_birth": Date | null;
        "race": string | null;
        "gender": string | null;
        "has_consent_text": boolean | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["first_name", String],
            ["last_name", String],
            ["email", String],
            ["phone", String],
            ["has_consent_marketing", Boolean],
            ["medical_record_number", String],
            ["date_of_birth", Date],
            ["race", String],
            ["gender", String],
            ["has_consent_text", Boolean],
        ] as const,
    };
}

export namespace PdsAddressPersonRelationship {
    export const name = "pds_address_person_relationship";
    
    export type t = {
        "created_at": Date;
        "updated_at": Date;
        "pds_address_uid": string;
        "pds_person_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_address_uid", String],
            ["pds_person_uid", String],
        ] as const,
    };
}

export namespace PdsMedication {
    export const name = "pds_medication";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_system_uid": string;
        "entity_id": string;
        "name": string;
        "ndc": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["name", String],
            ["ndc", String],
        ] as const,
    };
}

export namespace PdsPersonMedicationRelationship {
    export const name = "pds_person_medication_relationship";
    
    export type t = {
        "created_at": Date;
        "updated_at": Date;
        "pds_person_uid": string;
        "pds_medication_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_person_uid", String],
            ["pds_medication_uid", String],
        ] as const,
    };
}

export namespace Campaign {
    export const name = "campaign";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "person_uid": string;
        "ft_state_uid": string;
        "state": CampaignState.t;
        "stored_metadata": any;
        "practice_uid": string;
        "experiment_uid": string | null;
        "experiment_split_uid": string | null;
        "flags": any;
        "practice_phone_uid": string | null;
        "campaign_class_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["ft_state_uid", String],
            ["state", CampaignState.spec],
            ["stored_metadata", Object],
            ["practice_uid", String],
            ["experiment_uid", String],
            ["experiment_split_uid", String],
            ["flags", Object],
            ["practice_phone_uid", String],
            ["campaign_class_uid", String],
        ] as const,
    };
}

export namespace PersonChannelFdMap {
    export const name = "person_channel_fd_map";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "person_uid": string;
        "channel_fd_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["channel_fd_uid", String],
        ] as const,
    };
}

export namespace FtvmCache {
    export const name = "ftvm_cache";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "program_slug": string;
        "cache_key": string;
        "cache_value": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["program_slug", String],
            ["cache_key", String],
            ["cache_value", Object],
        ] as const,
    };
}

export namespace ProgramCacheStatus {
    export const name = "program_cache_status";
    
    export type t = {
        "program_uid": string;
        "cache_primed": boolean;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["program_uid", String],
            ["cache_primed", Boolean],
        ] as const,
    };
}

export namespace PdsStagedExport {
    export const name = "pds_staged_export";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_system_uid": string;
        "data_row": any;
        "done": boolean;
        "file_name": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["data_row", Object],
            ["done", Boolean],
            ["file_name", String],
        ] as const,
    };
}

export namespace ShortLink {
    export const name = "short_link";
    
    export type t = {
        "slug": string;
        "domain": string;
        "created_at": Date;
        "updated_at": Date;
        "uri": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["slug", String],
            ["domain", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["uri", String],
        ] as const,
    };
}

export namespace PersonConsent {
    export const name = "person_consent";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "person_uid": string;
        "status": ConsentStatus.t;
        "surface": ConsentSurface.t | null;
        "consent_text": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["status", ConsentStatus.spec],
            ["surface", ConsentSurface.spec],
            ["consent_text", String],
        ] as const,
    };
}

export namespace ConsentChannelFdMap {
    export const name = "consent_channel_fd_map";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "person_uid": string;
        "channel_fd_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["channel_fd_uid", String],
        ] as const,
    };
}

export namespace PipeContent {
    export const name = "pipe_content";
    
    export type t = {
        "channel_fd_uid": string;
        "created_at": Date;
        "content": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["channel_fd_uid", String],
            ["created_at", Date],
            ["content", Object],
        ] as const,
    };
}

export namespace EvalSpec {
    export const name = "eval_spec";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "program_slug": string;
        "version": number;
        "spec": any;
        "pass_ratio": number;
        "attempts": number;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["program_slug", String],
            ["version", Number],
            ["spec", Object],
            ["pass_ratio", Number],
            ["attempts", Number],
        ] as const,
    };
}

export namespace EvalResult {
    export const name = "eval_result";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "eval_spec_uid": string;
        "program_uid": string;
        "status": EvalResultStatus.t;
        "success_rate": number | null;
        "result": any | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["eval_spec_uid", String],
            ["program_uid", String],
            ["status", EvalResultStatus.spec],
            ["success_rate", Number],
            ["result", Object],
        ] as const,
    };
}

export namespace AnalyticsBatch {
    export const name = "analytics_batch";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "status": AnalyticsBatchStatus.t;
        "description": string;
        "search_query": any | null;
        "selected_analytics": any | null;
        "kind": AnalyticsBatchKind.t;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["status", AnalyticsBatchStatus.spec],
            ["description", String],
            ["search_query", Object],
            ["selected_analytics", Object],
            ["kind", AnalyticsBatchKind.spec],
        ] as const,
    };
}

export namespace AnalyticsCampaignObservation {
    export const name = "analytics_campaign_observation";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "analytics_batch_uid": string;
        "campaign_uid": string;
        "done": boolean;
        "results": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["analytics_batch_uid", String],
            ["campaign_uid", String],
            ["done", Boolean],
            ["results", Object],
        ] as const,
    };
}

export namespace PdsSftpLocalEgressFile {
    export const name = "pds_sftp_local_egress_file";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_registration_uid": string;
        "export_timestamp": Date;
        "file_name": string;
        "body": Buffer;
        "is_deleted": boolean | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_registration_uid", String],
            ["export_timestamp", Date],
            ["file_name", String],
            ["body", Buffer],
            ["is_deleted", Boolean],
        ] as const,
    };
}

export namespace Pipeline {
    export const name = "pipeline";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "name": string;
        "description": string | null;
        "last_indexed_record": Date | null;
        "practice_uid": string;
        "source": PipelineSource.t;
        "active": boolean;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["name", String],
            ["description", String],
            ["last_indexed_record", Date],
            ["practice_uid", String],
            ["source", PipelineSource.spec],
            ["active", Boolean],
        ] as const,
    };
}

export namespace PipelineDefinition {
    export const name = "pipeline_definition";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pipeline_uid": string;
        "version": number;
        "definition": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pipeline_uid", String],
            ["version", Number],
            ["definition", Object],
        ] as const,
    };
}

export namespace PipelineBatchCache {
    export const name = "pipeline_batch_cache";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pipeline_definition_uid": string;
        "rows": Buffer;
        "current_step": number;
        "stage": number | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pipeline_definition_uid", String],
            ["rows", Buffer],
            ["current_step", Number],
            ["stage", Number],
        ] as const,
    };
}

export namespace SystemEvent {
    export const name = "system_event";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "kind": SystemEventKind.t;
        "data": any;
        "practice_uid": string;
        "person_uid": string | null;
        "campaign_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["kind", SystemEventKind.spec],
            ["data", Object],
            ["practice_uid", String],
            ["person_uid", String],
            ["campaign_uid", String],
        ] as const,
    };
}

export namespace TimerContent {
    export const name = "timer_content";
    
    export type t = {
        "channel_fd_uid": string;
        "created_at": Date;
        "fire_time": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["channel_fd_uid", String],
            ["created_at", Date],
            ["fire_time", Date],
        ] as const,
    };
}

export namespace EmailVerificationToken {
    export const name = "email_verification_token";
    
    export type t = {
        "token": string;
        "email": string;
        "user_auth_uid": string;
        "created_at": Date;
        "expires_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["token", String],
            ["email", String],
            ["user_auth_uid", String],
            ["created_at", Date],
            ["expires_at", Date],
        ] as const,
    };
}

export namespace VerifiedEmail {
    export const name = "verified_email";
    
    export type t = {
        "uid": string;
        "user_auth_uid": string;
        "email": string;
        "created_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["user_auth_uid", String],
            ["email", String],
            ["created_at", Date],
        ] as const,
    };
}

export namespace PiquedHead {
    export const name = "_piqued_head";
    
    export type t = {
        "index_key": number;
        "head": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["index_key", Number],
            ["head", String],
        ] as const,
    };
}

export namespace PracticePersonStaffOld {
    export const name = "_practice_person_staff_old";
    
    export type t = {
        "practice_uid": string;
        "person_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["practice_uid", String],
            ["person_uid", String],
        ] as const,
    };
}

export namespace PracticePersonPatientOld {
    export const name = "_practice_person_patient_old";
    
    export type t = {
        "practice_uid": string;
        "person_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["practice_uid", String],
            ["person_uid", String],
        ] as const,
    };
}

export namespace PatientList {
    export const name = "patient_list";
    
    export type t = {
        "person_uid": string | null;
        "practice_uid": string | null;
        "person": Person.t | null;
        "medications": PharmacyItem.t[] | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["person_uid", String],
            ["practice_uid", String],
            ["person", Person.spec],
            ["medications", { "kind": "array", "spec": PharmacyItem.spec }],
        ] as const,
    };
}

export namespace PracticePerson {
    export const name = "practice_person";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "practice_uid": string;
        "person_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["practice_uid", String],
            ["person_uid", String],
        ] as const,
    };
}

export namespace PracticePersonRole {
    export const name = "practice_person_role";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "practice_person_uid": string;
        "role": PersonRole.t;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["practice_person_uid", String],
            ["role", PersonRole.spec],
        ] as const,
    };
}

export namespace PracticePersonDetail {
    export const name = "practice_person_detail";
    
    export type t = {
        "uid": string | null;
        "created_at": Date | null;
        "updated_at": Date | null;
        "person_uid": string | null;
        "first_name": string | null;
        "last_name": string | null;
        "email": string | null;
        "phone_number": string | null;
        "practice_uid": string | null;
        "practice_name": string | null;
        "roles": PersonRole.t[] | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["first_name", String],
            ["last_name", String],
            ["email", String],
            ["phone_number", String],
            ["practice_uid", String],
            ["practice_name", String],
            ["roles", { "kind": "array", "spec": PersonRole.spec }],
        ] as const,
    };
}

export namespace Outreach {
    export const name = "outreach";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "source": OutreachSource.t;
        "practice_uid": string;
        "target_uid": string;
        "assigned_staff_uid": string | null;
        "last_action_at": Date | null;
        "status_detail": OutreachStatusDetail.t;
        "status": OutreachStatus.t;
        "outreach_class_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["source", OutreachSource.spec],
            ["practice_uid", String],
            ["target_uid", String],
            ["assigned_staff_uid", String],
            ["last_action_at", Date],
            ["status_detail", OutreachStatusDetail.spec],
            ["status", OutreachStatus.spec],
            ["outreach_class_uid", String],
        ] as const,
    };
}

export namespace OutreachEvent {
    export const name = "outreach_event";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "outreach_uid": string;
        "type": OutreachEventType.t;
        "note": string;
        "author_uid": string | null;
        "hidden": boolean;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["outreach_uid", String],
            ["type", OutreachEventType.spec],
            ["note", String],
            ["author_uid", String],
            ["hidden", Boolean],
        ] as const,
    };
}

export namespace Experiment {
    export const name = "experiment";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "practice_uid": string;
        "name": string;
        "description": string | null;
        "program_slug": string;
        "program_version": number | null;
        "configuration_options": any;
        "feature_flags": any;
        "start_date": Date;
        "end_date": Date;
        "paused": boolean | null;
        "archived": boolean | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["practice_uid", String],
            ["name", String],
            ["description", String],
            ["program_slug", String],
            ["program_version", Number],
            ["configuration_options", Object],
            ["feature_flags", Object],
            ["start_date", Date],
            ["end_date", Date],
            ["paused", Boolean],
            ["archived", Boolean],
        ] as const,
    };
}

export namespace ExperimentSplit {
    export const name = "experiment_split";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "experiment_uid": string;
        "name": string;
        "percentage": number;
        "program_slug": string | null;
        "program_version": number | null;
        "configuration_options": any | null;
        "feature_flags": any | null;
        "archived": boolean;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["experiment_uid", String],
            ["name", String],
            ["percentage", Number],
            ["program_slug", String],
            ["program_version", Number],
            ["configuration_options", Object],
            ["feature_flags", Object],
            ["archived", Boolean],
        ] as const,
    };
}

export namespace PracticeAnalytics {
    export const name = "practice_analytics";
    
    export type t = {
        "practice_uid": string;
        "created_at": Date;
        "updated_at": Date;
        "last_indexed_record": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["practice_uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["last_indexed_record", Date],
        ] as const,
    };
}

export namespace PdsPrescriber {
    export const name = "pds_prescriber";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_system_uid": string;
        "entity_id": string;
        "npi": string | null;
        "dea": string | null;
        "first_name": string | null;
        "last_name": string | null;
        "phone_number": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["npi", String],
            ["dea", String],
            ["first_name", String],
            ["last_name", String],
            ["phone_number", String],
        ] as const,
    };
}

export namespace PdsPharmacy {
    export const name = "pds_pharmacy";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_system_uid": string;
        "entity_id": string;
        "ncpdp": string | null;
        "name": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["ncpdp", String],
            ["name", String],
        ] as const,
    };
}

export namespace PdsInsurance {
    export const name = "pds_insurance";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_system_uid": string;
        "entity_id": string;
        "plan_name": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["plan_name", String],
        ] as const,
    };
}

export namespace PdsPersonPrescriberRelationship {
    export const name = "pds_person_prescriber_relationship";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_prescriber_uid": string;
        "pds_person_uid": string;
        "last_visit": Date | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_prescriber_uid", String],
            ["pds_person_uid", String],
            ["last_visit", Date],
        ] as const,
    };
}

export namespace PdsPersonInsuranceRelationship {
    export const name = "pds_person_insurance_relationship";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_person_uid": string;
        "pds_insurance_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_person_uid", String],
            ["pds_insurance_uid", String],
        ] as const,
    };
}

export namespace PdsPrescription {
    export const name = "pds_prescription";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_person_uid": string;
        "pds_medication_uid": string;
        "pds_prescriber_uid": string | null;
        "pds_pharmacy_uid": string | null;
        "pds_insurance_uid": string | null;
        "description": string | null;
        "written_at": Date | null;
        "refills": number;
        "site": string | null;
        "days_supply": number | null;
        "diagnosis": string | null;
        "system_sent_ingested_at": Date | null;
        "expires_at": Date | null;
        "uid_old": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_person_uid", String],
            ["pds_medication_uid", String],
            ["pds_prescriber_uid", String],
            ["pds_pharmacy_uid", String],
            ["pds_insurance_uid", String],
            ["description", String],
            ["written_at", Date],
            ["refills", Number],
            ["site", String],
            ["days_supply", Number],
            ["diagnosis", String],
            ["system_sent_ingested_at", Date],
            ["expires_at", Date],
            ["uid_old", String],
        ] as const,
    };
}

export namespace PdsPrescriptionDetail {
    export const name = "pds_prescription_detail";
    
    export type t = {
        "uid": string | null;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_person_uid": string | null;
        "pds_medication_uid": string | null;
        "pds_prescriber_uid": string | null;
        "pds_pharmacy_uid": string | null;
        "pds_insurance_uid": string | null;
        "description": string | null;
        "written_at": Date | null;
        "pds_prescriber": PdsPrescriber.t | null;
        "pds_pharmacy": PdsPharmacy.t | null;
        "pds_insurance": PdsInsurance.t | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_person_uid", String],
            ["pds_medication_uid", String],
            ["pds_prescriber_uid", String],
            ["pds_pharmacy_uid", String],
            ["pds_insurance_uid", String],
            ["description", String],
            ["written_at", Date],
            ["pds_prescriber", PdsPrescriber.spec],
            ["pds_pharmacy", PdsPharmacy.spec],
            ["pds_insurance", PdsInsurance.spec],
        ] as const,
    };
}

export namespace LatestCampaignObservation {
    export const name = "latest_campaign_observation";
    
    export type t = {
        "uid": string | null;
        "created_at": Date | null;
        "updated_at": Date | null;
        "analytics_batch_uid": string | null;
        "campaign_uid": string | null;
        "done": boolean | null;
        "results": any | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["analytics_batch_uid", String],
            ["campaign_uid", String],
            ["done", Boolean],
            ["results", Object],
        ] as const,
    };
}

export namespace OneTimePassword {
    export const name = "one_time_password";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "expires_at": Date | null;
        "email": string;
        "password": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["expires_at", Date],
            ["email", String],
            ["password", String],
        ] as const,
    };
}

export namespace PdsFileParserMap {
    export const name = "pds_file_parser_map";
    
    export type t = {
        "uid": string;
        "pds_registration_uid": string;
        "regex": string;
        "parser_key": ParserKey.t;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["pds_registration_uid", String],
            ["regex", String],
            ["parser_key", ParserKey.spec],
        ] as const,
    };
}

export namespace PdsMedicationPricing {
    export const name = "pds_medication_pricing";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_system_uid": string;
        "entity_id": string;
        "ndc": string;
        "description": string | null;
        "price_wac": string | null;
        "price_340b": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["ndc", String],
            ["description", String],
            ["price_wac", String],
            ["price_340b", String],
        ] as const,
    };
}

export namespace AnalyticsPharmacyObservation {
    export const name = "analytics_pharmacy_observation";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "analytics_batch_uid": string;
        "pds_pharmacy_uid": string;
        "done": boolean;
        "results": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["analytics_batch_uid", String],
            ["pds_pharmacy_uid", String],
            ["done", Boolean],
            ["results", Object],
        ] as const,
    };
}

export namespace LatestPharmacyObservation {
    export const name = "latest_pharmacy_observation";
    
    export type t = {
        "uid": string | null;
        "created_at": Date | null;
        "updated_at": Date | null;
        "analytics_batch_uid": string | null;
        "pds_pharmacy_uid": string | null;
        "done": boolean | null;
        "results": any | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["analytics_batch_uid", String],
            ["pds_pharmacy_uid", String],
            ["done", Boolean],
            ["results", Object],
        ] as const,
    };
}

export namespace AggregationCache {
    export const name = "aggregation_cache";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "last_triggered_at": Date | null;
        "cache_key": string;
        "cache_value": any;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["last_triggered_at", Date],
            ["cache_key", String],
            ["cache_value", Object],
        ] as const,
    };
}

export namespace PracticePhone {
    export const name = "practice_phone";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "practice_uid": string;
        "phone_number": string;
        "label": string | null;
        "kind": PhoneKind.t | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["practice_uid", String],
            ["phone_number", String],
            ["label", String],
            ["kind", PhoneKind.spec],
        ] as const,
    };
}

export namespace CampaignClass {
    export const name = "campaign_class";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "name": string;
        "description": string | null;
        "type": CampaignType.t;
        "practice_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["name", String],
            ["description", String],
            ["type", CampaignType.spec],
            ["practice_uid", String],
        ] as const,
    };
}

export namespace CampaignDetail {
    export const name = "campaign_detail";
    
    export type t = {
        "uid": string | null;
        "created_at": Date | null;
        "updated_at": Date | null;
        "person_uid": string | null;
        "campaign_class_uid": string | null;
        "first_name": string | null;
        "last_name": string | null;
        "program_uid": string | null;
        "program_name": string | null;
        "program_version": number | null;
        "ft_state_uid": string | null;
        "stored_metadata": any | null;
        "state": CampaignState.t | null;
        "message_count": number | null;
        "practice_uid": string | null;
        "medical_record_number": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["campaign_class_uid", String],
            ["first_name", String],
            ["last_name", String],
            ["program_uid", String],
            ["program_name", String],
            ["program_version", Number],
            ["ft_state_uid", String],
            ["stored_metadata", Object],
            ["state", CampaignState.spec],
            ["message_count", Number],
            ["practice_uid", String],
            ["medical_record_number", String],
        ] as const,
    };
}

export namespace SyntheticMessageLog {
    export const name = "synthetic_message_log";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "person_uid": string;
        "last_updated_at": Date | null;
        "temperament": string;
        "occupation": string;
        "age": number;
        "practice_phone_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["person_uid", String],
            ["last_updated_at", Date],
            ["temperament", String],
            ["occupation", String],
            ["age", Number],
            ["practice_phone_uid", String],
        ] as const,
    };
}

export namespace FtCronTask {
    export const name = "ft_cron_task";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "ft_state_uid": string;
        "cron_specifier": string;
        "next_fire_at": Date;
        "method_name": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["ft_state_uid", String],
            ["cron_specifier", String],
            ["next_fire_at", Date],
            ["method_name", String],
        ] as const,
    };
}

export namespace PracticeDoc {
    export const name = "practice_doc";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "practice_uid": string;
        "id": string;
        "name": string;
        "description": string | null;
        "spec": any;
        "letterhead_src": string | null;
        "file_name": string | null;
        "subtitle": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["practice_uid", String],
            ["id", String],
            ["name", String],
            ["description", String],
            ["spec", Object],
            ["letterhead_src", String],
            ["file_name", String],
            ["subtitle", String],
        ] as const,
    };
}

export namespace PracticeTwilioCredential {
    export const name = "practice_twilio_credential";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "practice_uid": string;
        "sid": string;
        "auth_token": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["practice_uid", String],
            ["sid", String],
            ["auth_token", String],
        ] as const,
    };
}

export namespace StreamChannelFdMap {
    export const name = "stream_channel_fd_map";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "channel_fd_uid": string;
        "person_uid": string;
        "practice_phone_uid": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["channel_fd_uid", String],
            ["person_uid", String],
            ["practice_phone_uid", String],
        ] as const,
    };
}

export namespace OutreachClass {
    export const name = "outreach_class";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "practice_uid": string | null;
        "type": OutreachType.t;
        "name": string;
        "description": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["practice_uid", String],
            ["type", OutreachType.spec],
            ["name", String],
            ["description", String],
        ] as const,
    };
}

export namespace OutreachCampaignMap {
    export const name = "outreach_campaign_map";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "outreach_uid": string | null;
        "campaign_uid": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["outreach_uid", String],
            ["campaign_uid", String],
        ] as const,
    };
}

export namespace PdsPrescriptionFill {
    export const name = "pds_prescription_fill";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "pds_prescription_uid": string;
        "pds_pharmacy_uid": string | null;
        "fill_number": number;
        "filled_at": Date | null;
        "picked_up_at": Date | null;
        "cancelled": boolean;
        "uid_old": string | null;
        "pds_prescription_uid_old": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_prescription_uid", String],
            ["pds_pharmacy_uid", String],
            ["fill_number", Number],
            ["filled_at", Date],
            ["picked_up_at", Date],
            ["cancelled", Boolean],
            ["uid_old", String],
            ["pds_prescription_uid_old", String],
        ] as const,
    };
}

export namespace PdsPersonDetail {
    export const name = "pds_person_detail";
    
    export type t = {
        "uid": string | null;
        "created_at": Date | null;
        "updated_at": Date | null;
        "pds_system_uid": string | null;
        "entity_id": string | null;
        "first_name": string | null;
        "last_name": string | null;
        "email": string | null;
        "phone": string | null;
        "has_consent_marketing": boolean | null;
        "medical_record_number": string | null;
        "date_of_birth": Date | null;
        "race": string | null;
        "gender": string | null;
        "has_consent_text": boolean | null;
        "prescribers": PdsPrescriber.t[] | null;
        "insurances": PdsInsurance.t[] | null;
        "pharmacies": PdsPharmacy.t[] | null;
        "medications": PdsMedication.t[] | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["pds_system_uid", String],
            ["entity_id", String],
            ["first_name", String],
            ["last_name", String],
            ["email", String],
            ["phone", String],
            ["has_consent_marketing", Boolean],
            ["medical_record_number", String],
            ["date_of_birth", Date],
            ["race", String],
            ["gender", String],
            ["has_consent_text", Boolean],
            ["prescribers", { "kind": "array", "spec": PdsPrescriber.spec }],
            ["insurances", { "kind": "array", "spec": PdsInsurance.spec }],
            ["pharmacies", { "kind": "array", "spec": PdsPharmacy.spec }],
            ["medications", { "kind": "array", "spec": PdsMedication.spec }],
        ] as const,
    };
}

export namespace FillIntent {
    export const name = "fill_intent";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "message_at": Date;
        "intent": Intent.t;
        "comment": string | null;
        "pds_prescription_uid": string;
        "fill_number": number;
        "pds_prescription_uid_old": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["message_at", Date],
            ["intent", Intent.spec],
            ["comment", String],
            ["pds_prescription_uid", String],
            ["fill_number", Number],
            ["pds_prescription_uid_old", String],
        ] as const,
    };
}

export namespace NamedChannelFdMap {
    export const name = "named_channel_fd_map";
    
    export type t = {
        "uid": string;
        "created_at": Date;
        "updated_at": Date;
        "channel_fd_uid": string;
        "name": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["channel_fd_uid", String],
            ["name", String],
        ] as const,
    };
}

export namespace RaisInsurance {
    export const name = "rais_insurance";
    
    export type t = {
        "uid": string;
        "created_at": Date | null;
        "updated_at": Date | null;
        "plan_name": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["uid", String],
            ["created_at", Date],
            ["updated_at", Date],
            ["plan_name", String],
        ] as const,
    };
}

export namespace ShippingStatus {
    export const name = "shipping_status";
    
    export type t =
        | "ORDER_CREATED"
        | "LABEL_CREATED"
        | "SHIPPED"
        | "DELIVERED"
        | "LOST"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "ORDER_CREATED",
            "LABEL_CREATED",
            "SHIPPED",
            "DELIVERED",
            "LOST",
        ] as const,
    };
}


export namespace MedicationStatus {
    export const name = "medication_status";
    
    export type t =
        | "ACTIVE"
        | "PAST"
        | "UNKNOWN"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "ACTIVE",
            "PAST",
            "UNKNOWN",
        ] as const,
    };
}


export namespace PatientAdherenceType {
    export const name = "patient_adherence_type";
    
    export type t =
        | "ACTIVE"
        | "INACTIVE"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "ACTIVE",
            "INACTIVE",
        ] as const,
    };
}


export namespace FsmNodeKind {
    export const name = "fsm_node_kind";
    
    export type t =
        | "SEND_MESSAGE"
        | "CONNECT_PATIENT"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "SEND_MESSAGE",
            "CONNECT_PATIENT",
        ] as const,
    };
}


export namespace FsmEdgeTrigger {
    export const name = "fsm_edge_trigger";
    
    export type t =
        | "FALLBACK"
        | "PATIENT_RESPONSE"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "FALLBACK",
            "PATIENT_RESPONSE",
        ] as const,
    };
}


export namespace Channel {
    export const name = "channel";
    
    export type t =
        | "SMS"
        | "IN_APP"
        | "EMAIL"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "SMS",
            "IN_APP",
            "EMAIL",
        ] as const,
    };
}


export namespace MessageStatus {
    export const name = "message_status";
    
    export type t =
        | "PENDING"
        | "SENT"
        | "DELIVERED"
        | "READ"
        | "FAILED"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "PENDING",
            "SENT",
            "DELIVERED",
            "READ",
            "FAILED",
        ] as const,
    };
}


export namespace MessageMode {
    export const name = "message_mode";
    
    export type t =
        | "OUTGOING"
        | "INCOMING"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "OUTGOING",
            "INCOMING",
        ] as const,
    };
}


export namespace ChannelKind {
    export const name = "channel_kind";
    
    export type t =
        | "PIPE"
        | "TIMER"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "PIPE",
            "TIMER",
        ] as const,
    };
}


export namespace PdsFileStatus {
    export const name = "pds_file_status";
    
    export type t =
        | "PENDING"
        | "INGESTED"
        | "PROCESSED"
        | "INVALID_NAME"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "PENDING",
            "INGESTED",
            "PROCESSED",
            "INVALID_NAME",
        ] as const,
    };
}


export namespace PdsFileBatchStatus {
    export const name = "pds_file_batch_status";
    
    export type t =
        | "INGESTED"
        | "PROCESSED"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "INGESTED",
            "PROCESSED",
        ] as const,
    };
}


export namespace CampaignState {
    export const name = "campaign_state";
    
    export type t =
        | "CREATED"
        | "ACTIVE"
        | "PAUSED"
        | "COMPLETED"
        | "ENGAGED"
        | "STALE"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CREATED",
            "ACTIVE",
            "PAUSED",
            "COMPLETED",
            "ENGAGED",
            "STALE",
        ] as const,
    };
}


export namespace PdsRegistrationProtocol {
    export const name = "pds_registration_protocol";
    
    export type t =
        | "LOCAL_SFTP"
        | "REMOTE_SFTP"
        | "HTTPS"
        | "SYNTHETIC_DATA"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "LOCAL_SFTP",
            "REMOTE_SFTP",
            "HTTPS",
            "SYNTHETIC_DATA",
        ] as const,
    };
}


export namespace ConsentSurface {
    export const name = "consent_surface";
    
    export type t =
        | "CRXR"
        | "PROVIDER"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CRXR",
            "PROVIDER",
        ] as const,
    };
}


export namespace ConsentStatus {
    export const name = "consent_status";
    
    export type t =
        | "PENDING"
        | "ACCEPTED"
        | "REJECTED"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "PENDING",
            "ACCEPTED",
            "REJECTED",
        ] as const,
    };
}


export namespace EvalResultStatus {
    export const name = "eval_result_status";
    
    export type t =
        | "PENDING"
        | "SUCCESS"
        | "FAILURE"
        | "ERROR"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "PENDING",
            "SUCCESS",
            "FAILURE",
            "ERROR",
        ] as const,
    };
}


export namespace AnalyticsBatchStatus {
    export const name = "analytics_batch_status";
    
    export type t =
        | "PENDING"
        | "COMPLETED"
        | "FAILED"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "PENDING",
            "COMPLETED",
            "FAILED",
        ] as const,
    };
}


export namespace PipelineSource {
    export const name = "pipeline_source";
    
    export type t =
        | "PDS_PERSON"
        | "PDS_FILL"
        | "FILL_INTENT"
        | "EL_CAMPAIGN_STATE_CHANGE"
        | "EL_CAMPAIGN_REPORT"
        | "PDS_PRESCRIPTION"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "PDS_PERSON",
            "PDS_FILL",
            "FILL_INTENT",
            "EL_CAMPAIGN_STATE_CHANGE",
            "EL_CAMPAIGN_REPORT",
            "PDS_PRESCRIPTION",
        ] as const,
    };
}


export namespace SystemEventKind {
    export const name = "system_event_kind";
    
    export type t =
        | "CAMPAIGN_STATE_CHANGE"
        | "CAMPAIGN_REPORT"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CAMPAIGN_STATE_CHANGE",
            "CAMPAIGN_REPORT",
        ] as const,
    };
}


export namespace PersonRole {
    export const name = "person_role";
    
    export type t =
        | "STAFF"
        | "PATIENT"
        | "ADMIN"
        | "OPERATIONS"
        | "OPERATIONS_MANAGER"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "STAFF",
            "PATIENT",
            "ADMIN",
            "OPERATIONS",
            "OPERATIONS_MANAGER",
        ] as const,
    };
}


export namespace OutreachSource {
    export const name = "outreach_source";
    
    export type t =
        | "CAMPAIGN"
        | "MANUAL"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CAMPAIGN",
            "MANUAL",
        ] as const,
    };
}


export namespace OutreachEventType {
    export const name = "outreach_event_type";
    
    export type t =
        | "CREATED"
        | "COMMENT"
        | "STATUS_CHANGE"
        | "MISSED"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CREATED",
            "COMMENT",
            "STATUS_CHANGE",
            "MISSED",
        ] as const,
    };
}


export namespace AnalyticsBatchKind {
    export const name = "analytics_batch_kind";
    
    export type t =
        | "CAMPAIGN"
        | "PHARMACY"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CAMPAIGN",
            "PHARMACY",
        ] as const,
    };
}


export namespace ParserKey {
    export const name = "parser_key";
    
    export type t =
        | "SOMC_PATIENT_DATA"
        | "SOMC_WAC"
        | "SOMC_340B"
        | "SOMC_RX_30"
        | "CRX_UPSERT"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "SOMC_PATIENT_DATA",
            "SOMC_WAC",
            "SOMC_340B",
            "SOMC_RX_30",
            "CRX_UPSERT",
        ] as const,
    };
}


export namespace CampaignType {
    export const name = "campaign_type";
    
    export type t =
        | "REFILL"
        | "CAPTURE"
        | "ENGAGEMENT"
        | "OTHER"
        | "ADHERENCE"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "REFILL",
            "CAPTURE",
            "ENGAGEMENT",
            "OTHER",
            "ADHERENCE",
        ] as const,
    };
}


export namespace PdsRegistrationFormat {
    export const name = "pds_registration_format";
    
    export type t =
        | "CSV"
        | "JSONL"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CSV",
            "JSONL",
        ] as const,
    };
}


export namespace PhoneKind {
    export const name = "phone_kind";
    
    export type t =
        | "SMS"
        | "SYNTHETIC"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "SMS",
            "SYNTHETIC",
        ] as const,
    };
}


export namespace OutreachType {
    export const name = "outreach_type";
    
    export type t =
        | "CAPTURE"
        | "DATA_COLLECTION"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "CAPTURE",
            "DATA_COLLECTION",
        ] as const,
    };
}


export namespace OutreachStatusDetail {
    export const name = "outreach_status_detail";
    
    export type t =
        | "ACTIVE"
        | "WON"
        | "DECLINED"
        | "UNREACHABLE"
        | "PAYOR_LOCKOUT"
        | "AWAITING_PATIENT"
        | "COMPLETED"
        | "MEDICATION_DISCONTINUED"
        | "ALREADY_ENROLLED"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "ACTIVE",
            "WON",
            "DECLINED",
            "UNREACHABLE",
            "PAYOR_LOCKOUT",
            "AWAITING_PATIENT",
            "COMPLETED",
            "MEDICATION_DISCONTINUED",
            "ALREADY_ENROLLED",
        ] as const,
    };
}


export namespace OutreachStatus {
    export const name = "outreach_status";
    
    export type t =
        | "IN_PROGRESS"
        | "SUCCESS"
        | "FAILURE"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "IN_PROGRESS",
            "SUCCESS",
            "FAILURE",
        ] as const,
    };
}


export namespace Intent {
    export const name = "intent";
    
    export type t =
        | "WANTS"
        | "NO_WANTS"
        | "UNDECIDED"
        | "HAS_QUESTIONS"
        ;
    
    export const spec = {
        kind: "enum" as const,
        values: [
            "WANTS",
            "NO_WANTS",
            "UNDECIDED",
            "HAS_QUESTIONS",
        ] as const,
    };
}


