[target.x86_64-unknown-linux-gnu]
linker = "clang"
pre-build = [
    "apt-get --assume-yes install libclang-5.0-dev clang-5.0",
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
pre-build = [
    "apt-get --assume-yes install libclang-5.0-dev clang-5.0",
]